# The Project
site_name: THU-Stat-Wiki
site_description: THU Stat Wiki 是一个清华统辅课信息的汇聚站点，为大家学习统计知识、打破信息壁垒提供一个良好的平台。
site_author: THU Stat Wiki Team
site_url: https://thu-stat-wiki.github.io

# Repository
repo_name: THU Stat Wiki
repo_url: https://github.com/thu-stat-wiki/thu-stat-wiki.github.io

# Copyright
copyright: 'Copyright &copy; 2023 THU Stat Wiki Team'

# Content nav
nav:
  - 首页: 
    - Welcome: index.md
    - 关于: main/about.md
    - 加入我们: main/join.md
    - F.A.Q.: main/FAQ.md
  - 统计课程:
    - 统计课程: course/index.md
    - 树洞统辅课程测评搬运:
      - course/thuhole122635/index.md
      - 课程教师: course/thuhole122635/instructor.md
      - 课程测评: course/thuhole122635/course.md
      - 先修关系: course/thuhole122635/workflow.md
      - 引用资源: course/thuhole122635/resource.md
  - 知识:
    - 知识: knowledge/index.md
  - 科研相关:
    - 科研相关: research/index.md
  - 保研出国:
    - 保研出国: placement/index.md
  - 实用链接:
    - 实用链接: link/index.md


# Theme
theme:
  name: material
  icon:
    # logo: material/sigma-lower
    
    repo: fontawesome/brands/git-alt
  logo: assets/icon/logo.png
  favicon: assets/icon/favicon.jpg
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: deep purple
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: deep purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.indexes 
    - navigation.top
    - header.autohide
    - announce.dismiss
    - navigation.footer
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'



# Others
extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

plugins:
  - search:
      lang:
          - en
          - ja
      separator: '[\s\-\.]+'

extra:
  social:
    - icon: material/link
      link: http://www.stat.tsinghua.edu.cn
      name: Tsinghua Statistics

markdown_extensions:
  - abbr
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.progressbar

