site_name: THU-Stat-Wiki
theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  custom_dir: overrides
